version: '3'
services:
  rabbitmq-server:
    image: rabbitmq:3.8-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  publisher:
    build: ./publisher
    depends_on:
      - rabbitmq-server
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq-server
      - RABBITMQ_PORT=5672
    ports:
      - "3000:3000"
    volumes:
      - "./publisher:/publisher"

  subscriber:
    build: ./subscriber
    depends_on:
      - rabbitmq-server
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq-server
      - RABBITMQ_PORT=5672
    volumes:
      - "./subscriber:/subscriber"

volumes:
  publisher:
  subscriber:


